### ISSUE TITLE
Ember-shepherd extension

### ISSUE THREAD

**Issue by RobbieTheWagner** [thiagoc7/ember-onboarding#1]
Hi @thiagoc7. I like some of the things you have done here. Would you be interested in working together with me on ember-shepherd to make it work more like you would like it to? I think we could allow for multiple options to exist, that would work with small and large requirements alike. It would be great to collaborate and make one truly great product together, instead of working separately. If not, no worries, but just thought I would reach out.

**Comment by thiagoc7** [comment]
Hi @rwwagner90, we can do it!
How do you plan to make it happen?

**Comment by RobbieTheWagner** [comment]
I didn't have a plan for it, necessarily, I figure we could take it one piece at a time. First step would be to get a list of things we want to support and agree on a syntax for them. You know better than me the reasons you created this project, so let's start with supporting those shortcomings and go from there. You tell me where you want to start :).

**Comment by RobbieTheWagner** [comment]
What is the first shortcoming of ember-shepherd that you'd like to address? I'd like to start trying to work together, so neither of us duplicate work.

**Comment by thiagoc7** [comment]
Hi @rwwagner90, sorry for delay.
I'm busy these days, but let's start.

I'll create a PR on your repo, and we talk there, ok?
I think it makes more sense.

Cheers!

**Comment by RobbieTheWagner** [comment]
Works for me!
