### ISSUE TITLE
Error: Attempting to inject an unknown injection: `service:onboard`

### ISSUE THREAD

**Issue by awwester** [thiagoc7/ember-onboarding#7]
I have a fresh install on the following versions:
ember-cli: 1.13.1
node: 0.12.1
npm: 2.12.1

I have tried deleting and reinstalling my node_modules a couple times, but I'm getting the error Error: Attempting to inject an unknown injection: `service:onboard` when putting `onboard: Ember.inject.service(),` in my application controller. I've checked the node_module install and I see that service installed correctly along with the ember addon.

**Comment by subho007** [comment]
@awwester are you still facing this problem? or else please close the issue
